---
title: "HW11"
author: "Seyedehbahareh Hashemimovahed"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 1.The names of all team members that worked on the final project;
Seyedehbahareh Hashemimovahed


#### 2.An overview of the data set you are working with for the final project;

Kidney Stone Dataset 
https://www.kaggle.com/datasets/harshghadiya/kidneystone

If I choose the Kidney stone, I will look at the variable in data to find what causes Kidney stone or what factors impact kidney stones,  such as increase or decrease the possibality of kidney stones. 

#### or 

NFL scores and betting data
https://www.kaggle.com/datasets/tobycrabtree/nfl-scores-and-betting-data

If I choose the NFL draft data, I'm going to focus on the NFL Devision Playoffs/rounds and compare them with None divisional playoffs.  



#### 3.Discussion of cleaning steps that are necessary to get the data into the right shape. 
Since I got the data from Kaggle, it already looks clean,  but to doublecheck, I will make sure to remove empty boxes,  and removing duplicates.  I might need to change the types on variables based on my needs on my data exploration on the dataset and the questions I am looking into. 
